Initial refactoring of the github workflow to publish modules on npmjs
Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Set dry run to test the github flow

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Specify the packagemanager to be used

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Enable corepack as it is needed to use packageManager yarn > 1.x

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Moving corepack enable before calling setup-node. See: https://github.com/actions/setup-node/issues/899

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing the hack folder as non needed anymore. Creating an empty yarn.lock file to avoid error: Dependencies lock file is not found

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Fix indentation issue

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Remove the deprecated parameter to use --immutable

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing the yarn install strep as it raises a yarn YN0028 error with lockfile

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Trying again to install the packages before to tsc compile

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Fix proposed by https://github.com/plone/volto-addon-ci/issues/11 concerning lockfile issue

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Deleting --immutable to try to fix issue of yarn YN0028

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Using --no-immutable

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Adding needed dependency as tsc fails with: TS2688: Cannot find type definition file for 'jest, node'

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

intall jest

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Run foreach to install missing node modules

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Let's use the backstage action instead ;-)

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Pusing yarn.lock

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Using same packageManager version as backstage

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Use same action defintion as backstage

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Updating yarn.lock file

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing spaces

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Adding .nmprc file

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Enabling again corepack as we will use yarn package manager > 1.x

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Let's try a build using node 18.x as 20.x fails on ci platform

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Switch from tsc:full to tsc

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

adding to tsc --skipLibCheck false --incremental false

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

adding to tsc --skipLibCheck false --incremental false

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Use workspaces foreach tsc

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing tsc:full as it do not exist

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Install the command supporting foreach subcommand

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

List the plugin installed

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

List the plugin installed

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Checking what we have as executable under node_modules/.bin

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing trailing ,

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Refactor the workflow to use the action of janus-idp project

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Push the missing .nvmrc file

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing packageManager > 1.x

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing yarn.lock

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Set cache-dependency-path

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Generating the package-lock.json

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Split tsc and build steps

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing unknow parameter

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing unknow parameter

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Use turbo commands

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Add turbo.json config file

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Define the needed config files able to find the generated .d.ts

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Let's try using turbo ...

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Remove cache parameter

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Adding needed yarn.lock

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Check files generated

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Adding missing shell parameter

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing non accessible folder

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Moving step to ci.yaml file

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Add comments and test using node 20.x too

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Published the modules manually and updated project

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Fix wrong file to be used to publish: dist/index.cjs.js to dist/index.esm.js for the frontend

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Bump versions published

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Remove non needed dependency as we dont use yarn workspaces foreach

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Align with latest versions published

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing non needed file

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Removing non needed file

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Adding the needed scripts used to switch from src files to dist files when we pack or publish otherwise the package.json published will point to the src files and not the compiled !

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Ignore this file package.json-prepack

Signed-off-by: cmoulliard <cmoulliard@redhat.com>

Passing the version of node to be used using an input parameter to the action

Signed-off-by: cmoulliard <cmoulliard@redhat.com>